theme = "base16_transparent"

[editor]
shell= ["fish", "-c"]
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[editor.whitespace.render]
tab = "all"

[editor.soft-wrap]
enable = true

[editor.lsp]
display-messages = true

[editor.indent-guides]
character = "╎"
render = true
skip-levels = 1

[keys.normal]
X = "select_line_above"
esc = ["collapse_selection", "keep_primary_selection"]
# "drag" selections
A-h = ["delete_selection", "ensure_selections_forward", "flip_selections", "move_char_left", "paste_before"]
A-j = ["delete_selection", "move_visual_line_up", "paste_before"]
A-k = ["delete_selection", "move_visual_line_down", "paste_after"]
A-l = ["delete_selection", "ensure_selections_forward", "paste_after"]

[keys.insert]
A-h = [":toggle lsp.auto-signature-help", "normal_mode", "insert_mode"]
C-backspace = "delete_word_backward"
C-del = "delete_word_forward"
C-left = "move_prev_word_start"
C-right = ["move_next_word_end", "move_char_right"]

[editor.statusline]
mode.normal = "Normal"
mode.insert = "Insert"
mode.select = "Select"
